/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'click count': '点击数量',
    'cost': '成本',
    'cooldown': '冷却',
    'export': '导出',
    'import': '导入',
    'get': '获得',
    'hover on': '悬浮查看',
    'left': '剩余',
    'locked': '未解锁',
    'max pps': '最大能量每秒',
    'myst upgrade': '神秘升级',
    'myst upgrades': '神秘升级',
    'need': '需要',
    'omega rune': '欧米咖符文',
    'overall score': '总分',
    'owo': '哇',
    'playtime': '游戏时间',
    'play time(hour': '游戏时长 (小时',
    'reach': '达到',
    'rebuild': '重建',
    'save': '保存',
    'speed /': '速度 /',
    'time left': '时间剩余',
    'upgrade': '升级',
    'upgrades': '升级',
    'bps': '方块每秒',
    'click': '点击',
    'cheat': '作弊',
    'cancel': '取消',
    'score': '分数',
    'toggle': '切换',
    'time speed x': '时间速度 x',
    'token': '令牌',
    'block': '方块',
    'reset': '重置',
    'status': '状态',
    'to beyond': '超越',
    'used': '用过',
    'buildings': '建筑',
    'building mult.': '建筑相乘。',
    'auto': '自动',
    'base value': '基值',
    'block/s': '方块/秒',
    'blocks': '方块',
    'blocks)': '方块)',
    'blocks use/click': '方块 使用/点击',
    'boost used': '已用提升',
    'build': '建造',
    'building': '建筑',
    '-play time(hour': '-游戏时间(小时',
    '-pure bpc': '-净每次点击获得的方块',
    '-pure bps': '-净每秒获得的方块',
    '-click count': '-点击次数',
    '-max pps': '-最大能量每秒',
    ' need': ' 需要',
    '-bps mult.': '-每秒获得的方块倍数',
    '-bpc mult.': '-每次点击获得的方块倍数',
    '-block used': '-已用的方块',
    '-boost used': '-已用的提升',
    '-bu eff mult.': '-建筑升级效果倍数',
    '-building mult.': '-建筑倍数',
    '-buildings': '-建筑',
    'chance': '几率',
    'hover on tree': '悬浮在树上',
    'multiplier: x': '倍数: x',
    'power': '能量',
    ' base value': ' 基数',
    'beyond point': '超越点',
    'bupc mult.': '建筑升级每次点击倍数',
    'gain': '获得',
    'production by x': '产量 x',
    'power/s': '能量/秒',
    'rebuild count': '重建数量',
    'rebuild multiplier: x': '重建倍数: x',
    'rotation tree': '旋转的树',
    'rune': '符文',
    '-myst upgrade': '-神秘升级',
    '-overall score': '-总分',
    '-rebuild count': '-重建数量',
    '-bupc mult.': '-建筑升级每次点击倍数',
    ' upgrade': '升级',
    ' time left': '时间剩余',
    'boost effect': '提升效果',
    'bupc': '建筑升级每次点击',
    'bu eff': '建筑升级效果',
    'boost cool -': '提升冷却-',
    'tok m': '令牌 m',
    'tok p': '令牌 p',
    'speed': '速度',
    'rune +': '符文 +',
    'production': '产量',
    'product': '',
    'product': '产品',
    'omega': '欧米伽',
    'no': '不',
    'master': '大师',
    'ascend': '转生',
    'autotarget power': '自动目标能量',
    'autotarget power to best effect': '自动目标能量到最佳效果',
    'b used': 'b 已使用',
    'beyond': '超越',
    'bp': '超越点',
    'bp +': '超越点 +',
    'bpc': '超越点每次点击',
    'error!': '错误!',
    'get extra bp': '获得额外的超越点',
    'game speed': '游戏速度',
    'pps x2 (': '能量每秒 x2 (',
    'token ': '令牌',
    'boost block production': '提升方块产量',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'add all runes level, but lose all progress': '添加所有符文等级，但失去所有进度',
    'boost': '提升',
    'boost base building efficiency': '提高基础建筑效率',
    'boost block production gained per building': '提高每座建筑物的方块产量',
    'boost token gain': '提升令牌收益',
    'divide': '分摊',
    'divide cost of building': '分摊建筑成本',
    'increases effect and time of boosts, but increases cost (x^': '会增加提升效果和提升时间，但会增加成本 (x^',
    'autobuy rune 5/s (priority: rune 10-> rune': '自动购买符文5/秒 (优先级:符文10->符文',
    'autobuy rune': '自动购买符文',
    'autobuy myst upgrade': '自动购买神秘升级',
    'all runes level +': '全部符文等级 +',
    'keep': '保留',
    'keep basic upgrade': '保留基础升级',
    'keep build': '保留建造',
    'keep build on reset (expect rebuild': '重置时保留建造(期望重建',
    'keep myst upgrade': '保留神秘升级',
    'keep myst upgrades on reset': '在重置时保留神秘升级',
    'keep token, rolled boost on reset': '保留令牌，在重置时回滚提升',
    'keep upgrades on reset': '在重置时保留升级',
    'make boost time and cooldown shorter, but greater boost': '使提升时间和冷却时间更短，但是有更高的提升',
    'other boosts you didnt pick work at reduced effect': '其他你没有选择的刺激作用是减少效应',
    'you can build again, but much harder to build and reduced effect': '可以再次建造，但更难以建造并降低效果',
    'each rebuilding multiply': '每个重建乘以',
    'each building multiply': '每座建筑乘以',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "total ": "总计",
    "-token ": "-令牌",
    "-total ": "-总计",
    "block ": "方块",
    "cost: ": "成本: ",
    " cost": " 成本",
    "rune cost ": "符文成本",
    "token/click": "令牌/点击",
    "pps block use ": "能量每秒方块使用 ",
    "level ": "等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " blocks": " 方块",
    " double click (": "双击 (",
    '+1/s auto block (': '+1/秒自动方块 (',
    '+1/s auto build (': '+1/秒自动建造 (',
    " token": " 令牌",
    " tokens": " 令牌",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^bps (\d+)\% \-> bpc$/, 'bps $1\% \-> bpc'],
    [/^(.+)block\/(.+) \-> bupc  \($/, '方块\/$2 \-> 建筑升级每次点击  \('],
    [/^better rune (\d+) formula$/, '更好的符文 $1 公式'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);